language: node_js
node_js:
- 6.10.0
notifications:
  email: false
  webhooks: https://ambrosio-tele.herokuapp.com/sacarinobot/travisci/133188453
  on_success: always
  on_failure: always
  on_start: always
before_script:
- npm install -g grunt-cli
deploy:
  api_key:
    secure: "ULbgT1zh14RPwd0Pd5WoA+Eda5gdQ36mLujyH7+WsSvlhUasExOhZ9sHZMJ0g9UcBwivEA65Xgc2ZtDtKynMm7exkOk4fcLOXRJM7rdZf5ZfvO52WtujuqrSJJupn9o8ihlkCwrISu+GUbS6G/icOW/GCYPrOKJ500AkcCB1XCdSIJLsoP9+J1rJ9nhjNWFbJyNQ++TYoWLEY7sJOrcHTOrJvTl+0z++c9+7ZFiPxK6ZmiShr8EjzdpRdpOTe2FcSdyWv1rvDLWzgkj0VbO2SPCptWXjUnq8X9999oNdMUohJ8QIAfxj2EPCBPhWAc5jBqN6eLJHQikJP6Ifgr9R2DjR6sSKX4so7RISPJg/0rYqnTKhQs9IbwjW47EftGygkejNSho37AtYNvWt9GnAQWMxOKm6dFkqsekiYtLtIiS0yH45aHkAmmHMeA5n3gSdnrNICB3sJ5W/bvvwOQfcBA5W2p9fvY1Dz13i81Aly45zajnFbmcKdIRVGVeowehSHhZwX5xgOzbA5KhgIHE2Sah7TPj+ERUj8bl1LO4i0mXKaJAUH7Cl+PY3LaAw4jm5px0NX4hbhX9LCgQuFgNj9O0jq6Jo7ySIzVGtqhfC+d5CDLXTiC+0TCETg9kcTNZ9pFGKdk1isdR9phvwApAVoQ1TjG/vqdaSHO33ixvGyLs="
  email:
    secure: "qIsYHGho+GZLfDkE1eOUI2qixdRMJfWXSA5cMn9P5TjIm492HrFG2M0Zqrp79OA5U4VztPc4dZtxqGwgUfLeEWMj1NVermHkr1ovhBqjbWXicJ38A2pBbgqGn4j/WAkonCXkywEF2FtmatKSeju8m6sK4MBTc06bjRvH7oVSDPUnZrieRJQJkaHBC22Xgaaf4B3ovPWN5ndh5Rxqmw171JKrel5ZI9m6CQpDPyGMAyOyNIAfXSmnawDEkIstKCGinvPDD61gM/tQucuzpyBJe4MUETxKS98b8z8qH7Vj9+jX+7pW9pe2gbcVpdMEFwsDk4jVS9e7DpOXsQGhywA3j2Q9AKGuLGKw88qqHhYCcar2UcZv3CJNT1ZJEyO1XZE4AmYQ3EIDhypaGHJiuK5CAt11dJiP3ntm8lzKWaNPO51wgo4/Z4coXb8SQluo7a8neBNF0UdcvSaUNmSoi5yV7gQso0gnu8F07QNBfK50gntST8p/RygQ0k8+Ue5W/zGZY/WlvIUVPvtznSVLVmwakeL8QVObbFMMj7gyW4SnwuPzkibp+JAnUSydAmfC1pNTlIY/zX49ttSX9DMZ/wk8Wb+WQQwu7ZhjIsNFi44KoQoZ4ABw266f+KdBziHikfNYXSbuDB5argU6nUzpmNFE8KMBKXTIgZ0s2iyvbjUoqK4="
  provider: npm
